package es.dawgroup2.juding.posts;

import es.dawgroup2.juding.users.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.sql.SQLException;

import static org.springframework.web.servlet.support.ServletUriComponentsBuilder.fromCurrentRequest;

@RestController
@RequestMapping("/api/admin/post")
public class AdminPostAPIController {

    @Autowired
    PostService postService;

    @Autowired
    UserService userService;

    /**
     * Returns a inflated page of registered posts.
     *
     * @param model Model.
     * @param page  Number of page requested.
     * @return Inflated page.
     */
    @GetMapping("/list")
    public ResponseEntity<Page<Post>> getPostPage(@RequestParam(required = false) Integer page) {
        int defPage = (page == null) ? 1 : page - 1;
        if (defPage < 0) return ResponseEntity.badRequest().build();
        Page<Post> requiredPage = postService.getPostsInPages(defPage, 10);
        if (requiredPage.hasContent())
            return ResponseEntity.ok(requiredPage);
        else
            return ResponseEntity.badRequest().build();
    }

    /**
     * This method inflates the individual post edit section view.
     *
     * @param model Post data model.
     * @param id    Current post id.
     * @return Individual post edit section view.
     */
    @GetMapping("/{idPost}")
    public ResponseEntity<Post> getPost(@PathVariable String idPost) {
        Post post = postService.findById(idPost);
        if (post != null)
            return ResponseEntity.ok(post);
        else
            return ResponseEntity.badRequest().build();
    }

    /**
     * This method creates a new post using the post creation form fields as parameters.
     * Image is optional. If it's not submitted, the previous image will be set.
     * Finally, the new post will be added to database by autogenerated Id.
     *
     * @param title Post title form field.
     * @param image Post image form field.
     * @param body  Post body form field.
     * @return Redirects to all post list view.
     * @throws IOException  In case of the image file input fails.
     * @throws SQLException In case the previous image is not found on database.
     */
    @PostMapping("/newPost")
    public ResponseEntity<Post> addNewPost(@RequestParam String title,
                                           @RequestParam MultipartFile image,
                                           @RequestParam String body,
                                           HttpServletRequest request) throws IOException, SQLException {
        Post post = new Post();
        Post newPost = postService.save(post, "New", title, image, body, request);
        return ResponseEntity.created(fromCurrentRequest().path("/api/admin/post/{idPost}").buildAndExpand(newPost.getIdPost()).toUri()).body(newPost);
    }


    /**
     * This method modifies a post (searched by Id) using the post creation form fields as parameters.
     * Image is optional. If it's not submitted, the previous image will be set.
     * Finally, the new post will be update from database.
     *
     * @param id    Current post id.
     * @param title Post title form field.
     * @param image Post image form field.
     * @param body  Post body form field.
     * @return Redirects to all post list view.
     * @throws IOException  In case of the image file input fails.
     * @throws SQLException In case the previous image is not found on database.
     */
    @PutMapping("/edit")
    public ResponseEntity<Post> updatePost(@RequestParam String id,
                                             @RequestParam String title,
                                             @RequestParam MultipartFile image,
                                             @RequestParam String body) throws IOException, SQLException {
        Post post = postService.findById(id);
        Post updatedPost = postService.save(post, "Update", title, image, body, null);
        if (post!= null){
            return ResponseEntity.ok(updatedPost);
        }
        else {
            return ResponseEntity.badRequest().build();
        }
    }


    /**
     * This method deletes a post (search by Id) form database.
     *
     * @param id Current post id.
     * @return Redirects to all post list view.
     */
    @DeleteMapping("/delete/{id}")
    public ResponseEntity<Post> deletePost(@PathVariable String id) {
        Post competition = postService.findById(id);
        postService.deleteById(id);
        if (competition != null){
            return ResponseEntity.ok(competition);
        }
        else {
            return ResponseEntity.notFound().build();
        }
    }
}
